resources:
  - namespace-secrets.yaml
  - auth-service/deployment.yaml
  - driver-service/deployment.yaml
  - trip-service/deployment.yaml
  - postgres/deployment.yaml
  - mongodb/deployment.yaml
  - redis/deployment.yaml
  - redisinsight/deployment.yaml
  - zookeeper/deployment.yaml
  - kafka/deployment.yaml
  - elasticsearch/deployment.yaml
  - logstash/deployment.yaml
  - kibana/deployment.yaml
